#!/bin/bash
#SBATCH --account=iit130
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=01:00:00
#SBATCH --job-name=SIRS
#SBATCH --output=SIRS-%j.out

source "$HOME/miniconda3/etc/profile.d/conda.sh"
conda activate fultonmarket

# ---- CHANGE THIS PER SYSTEM ----
MM_SYSTEM=MSX-2

export JAX_PLATFORMS=cpu
python 11-SIRS.py ${MM_SYSTEM}